### PR TITLE
Implement Haskell version simillar to Javascript version

### PR DESCRIPTION
**Pull request by DzyubSpirit**

### CODE REVIEW

**Review by tshemsedinov — APPROVED** [review]
But please remove `/simple/` folder from path before merge

**Comment by DzyubSpirit** [comment]
I want to make 2 versions: simple and real with separate folders.
I'm currently working on a different implementation showing how lenses implemented in [lens](http://hackage.haskell.org/package/lens) package. It's harder to understand but it's more powerful allowing to compose lenses, making lenses for optional values, traversing (work with multiple values ) structures, etc.
But I still can move all simple examples in Haskell folder and real implementation in the separate folder.
Do you think it's a good idea?

**Comment by tshemsedinov** [comment]
You can either put all examples `/Haskell/` because they are ordered by `?-name.js` so extended examples will follow simple ones or you can put extended examples to `/Haskell/extended` even without ordering by the first letter because extended examples may need require submodules and letter-ordering will be not good for naming. Now let's merge simple examples.

**Comment by DzyubSpirit** [comment]
Landed in caa0628383a6fd97a9cf276edc821da44fc1a9de

**Pull request closed without merging**
